tupla = ("pala","pelota","camiseta","pantalon")
print(tupla)
lista = list(tupla)
lista.append("mano")
print(lista)
print (lista [1])
print(len(lista))
lista[1:2]=["carro"]
print(lista)
lista.clear()
print (lista)